image:
  file: Dockerfile
tasks:
  # React app
  - init: >
      cd client/react &&
      nvm use &&
      npm install
    command: >
      npm run start
  # Angular app
  - init: >
      cd client/angular &&
      nvm use &&
      yes | npm install &&
      yes | npm install --only="dev"
    command: >
      ng serve
  # Node.js API
  - init: >
      cd server/node.js-express &&
      nvm use &&
      npm install &&
      npm install --only="dev"
    command: >
      npm run dev
  # ASP.NET MVC and API
  - init: >
      cd server/asp.net-core
    command: >
      dotnet watch run
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4200
  - port: 8888
  - port: 5000
