image:
  file: Dockerfile
tasks:
  - init: >
      cd client/angular &&
      nvm use &&
      yes | npm install &&
      yes | npm install --only="dev"
    command: >
      ng serve
  - init: >
      cd client/react &&
      nvm use &&
      npm install
    command: >
      npm start
ports:
  - port: 4200
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
