trigger:
- '*'

variables:
 - group: git-secure
 - name: buildConfiguration
   value: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool: 'Default'
    

    variables:      
      #dotnetSdkVersion: '3.1.100'
      dotnetSdkVersion: '2.2.x'

    steps:
#    - task: UseDotNet@2
#      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
#      inputs:
#        version: '$(dotnetSdkVersion)'
    - script: 'echo "<h1>Release notes for build  $(Build.DefinitionName)</h1>  <b>Build Number</b>  : $(Build.BuildNumber)   <br/> $(Build.BuildId) "> buildinfo.html'
      displayName: 'Write build info'
      workingDirectory: $(Build.ArtifactStagingDirectory)

    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false

    - script: 'git config --list'
      displayName: 'List known users'

    - script: 'git remote -v'
      displayName: 'List known remotes'

#    - script: 'git config user.name $(git-username)'
#      displayName: 'Set new git username'

#    - script: 'git config user.password $(git-pass)'
#      displayName: 'Set new git password'
      
#    - script: 'git tag $(Build.BuildNumber)'
#      displayName: 'Add Git Tag for Build Number'

#    - script: 'git push --tags'
#      displayName: 'Push tags'
    - task: git-tag-on-release-task@9
      inputs:
        staticTagName: 'Bld$(Build.BuildNumber)'

    - task: XplatGenerateReleaseNotes@2
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)\build-notes.md'
        templateLocation: 'InLine'
        inlinetemplate: |
          # Release notes 
          **Build Number**  : ${buildDetails.buildNumber} 
          **Build started** : ${buildDetails.startTime}  
          **Source Branch** : ${buildDetails.sourceBranch}  

          ### Associated work items  
          @@WILOOP@@  
          * ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
          @@WILOOP@@  

          ### Associated commits
          @@CSLOOP@@  
          * ** ID ${csdetail.id} ** Commited by:  ${csdetail.author.displayName} (${csdetail.author.uniqueName}) ${csdetail.message}
          @@CSLOOP@@
        delimiter: ':'
        fieldEquality: '='
        anyFieldContent: '*'

        
    - task: XplatGenerateReleaseNotes@2
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)\build-notes.html'
        templateLocation: 'InLine'
        inlinetemplate: |
          <h1> Build Notes ${buildDetails.buildNumber} </h1>
          <br/><b>Build Number</b> : ${buildDetails.buildNumber} 
          <br/><b>Build Started</b>: ${buildDetails.startTime}  
          <br/><b>Source Branch</b> : ${buildDetails.sourceBranch}  

          <h3>Associated work items</h3>
          @@WILOOP@@  
          <br/>* ${widetail.fields['System.WorkItemType']} ${widetail.id} ** Assigned by: ${widetail.fields['System.AssignedTo']}  ${widetail.fields['System.Title']}  
          @@WILOOP@@  

          <h3>Associated commits</h3>
          @@CSLOOP@@  
          <b>Commit by:  ${csdetail.author.displayName} <i>${csdetail.author.uniqueName}</i> </b> ID ${csdetail.id} <p> ${csdetail.message} </p> <hr/>
          @@CSLOOP@@
        delimiter: ':'
        fieldEquality: '='
        anyFieldContent: '*'
          
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'



 #Below are deployment stages
- stage: 'Dev'
  displayName: 'Deploy dev environment'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool: Default
    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:
          - script: whoami
          - download: current
            artifact: drop
          - task: git-tag-on-release-task@9
            inputs:
              staticTagName: 'DEV-$(Build.BuildNumber)'



- stage: 'Test'
  displayName: 'Deploy test environment'
  dependsOn: Dev
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: git-tag-on-release-task@9
            inputs:
              staticTagName: 'OPS-$(Build.BuildNumber)'



- stage: 'OPS'
  displayName: 'Deploy staging environment'
  dependsOn: Test
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-16.04'
    environment: OPS
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: git-branch-on-release-task@9
            inputs:
              staticTagName: 'OPS'
          - task: git-tag-on-release-task@9
            inputs:
              staticTagName: 'develop'
